/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "DIALOG.h"
//extern void send_udp_data(void);

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_RADIO_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_0  (GUI_ID_USER + 0x02)
#define ID_TEXT_1  (GUI_ID_USER + 0x03)
#define ID_TEXT_2  (GUI_ID_USER + 0x04)
#define ID_BUTTON_0  (GUI_ID_USER + 0x05)
#define ID_TEXT_3  (GUI_ID_USER + 0x06)
#define ID_HEADER_0  (GUI_ID_USER + 0x07)
#define ID_TEXT_4  (GUI_ID_USER + 0x08)
#define ID_TEXT_5  (GUI_ID_USER + 0x09)
#define ID_MULTIEDIT_0  (GUI_ID_USER + 0x010)
#include <stdio.h>

extern char RxBuf[200];
//extern int etat;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, -1, -1, 480, 272, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 330, 140, 80, 60, 0, 0x1403, 0 },
  { TEXT_CreateIndirect, "Auto", ID_TEXT_0, 350, 140, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Gant", ID_TEXT_1, 350, 160, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Nunchuck", ID_TEXT_2, 350, 180, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Envoi", ID_BUTTON_0, 328, 208, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sélection du mode", ID_TEXT_3, 329, 114, 91, 20, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "header", ID_HEADER_0, 0, 0, 480, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Supervison locale", ID_TEXT_4, 50, 7, 128, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Mode : -", ID_TEXT_5, 312, 7, 80, 20, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 0, 109, 268, 163, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
	WM_HWIN      hItem;
	int choix;
	char message[30];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
    //
    // Initialization of 'Multiedit'
    //

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Envoi'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
				choix = RADIO_GetValue(hItem);  
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
				//send_udp_data(); 
			
			switch (choix){
				case 0:	
				//sprintf(message,	"Mode : Auto %d", etat);
								TEXT_SetText(hItem, "Mode : Auto");
					break;
				case 1:	TEXT_SetText(hItem, "Mode : Gant");
					break;
				case 2:	TEXT_SetText(hItem, "Mode : Nunchuck");
					break;
				default: TEXT_SetText(hItem, "Mode : aucun");
					break;
			}
			//TEXT_SetText(hItem, message);
			// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_HEADER_0: // Notifications sent by 'header'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    
    //break;
  // USER START (Optionally insert additional message handling)
  // USER END
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
					MULTIEDIT_SetText(hItem, RxBuf);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
